sudo: required

language: python
python:
  - "3.6"

services:
  - docker

branches:
  only:
    - master
    - production

before_install:
  - bash scripts/before_install.sh

install:
  - make dev-env
  # workaround
  - pip install -U pytest

script:
  - set -e
  - make build-test-all DARGS="--build-arg TEST_ONLY_BUILD=1"

after_success:
  - bash scripts/after_success.sh