sudo: required

language: python
python:
  - "3.6"

services:
  - docker

branches:
  only:
    - master
    - production

before_install:
  - ./.travis/before_install.sh

install:
  - make dev-env

script:
  - set -e
  - make build-all

after_success:
  - ./.travis/after_success.sh